name: places
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^0.19.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
   - res/


fonts:
    - family: Roboto
      fonts:
        - assets: res/fonts/Roboto-Black.ttf
        - assets: res/fonts/Roboto-BlackItalic.ttf
        - assets: res/fonts/Roboto-Bold.ttf
        - assets: res/fonts/Roboto-BoldItalic.ttf
        - assets: res/fonts/Roboto-Italic.ttf
        - assets: res/fonts/Roboto-Light.ttf
        - assets: res/fonts/Roboto-LightItalic.ttf
        - assets: res/fonts/Roboto-Medium.ttf
        - assets: res/fonts/Roboto-MediumItalic.ttf
        - assets: res/fonts/Roboto-Regular.ttf
        - assets: res/fonts/Roboto-Thin.ttf
        - assets: res/fonts/Roboto-ThinItalic.ttf 
